### ISSUE TITLE
Remover margem mv-modal margin

### ISSUE THREAD

**Issue by marcusvy** [marcusvy/emeve-ui#10]
IE 11 e safari não renderizam corretamente
Precisa remover margem:
```css
.mv-modal {
 margin: 0 auto; // <-remover
}
```
