### ISSUE TITLE
mv-list-item não apresenta espaçamento de coluna

### ISSUE THREAD

**Issue by marcusvy** [marcusvy/emeve-ui#9]
mv-list-item não apresenta espaçamento de coluna
possível aparência:
```css
.mv-list-item {
  margin: 0 -0.5rem;
  padding-left: 0.5rem;
  padding-right: 0.5rem;
}
```
